defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:current
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
version: 2.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
      - run: npm t
      - run: npm run lint
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export CLOUDFLARE_ACCOUNT_ID=$CF_ACCOUT_ID' >> $BASH_ENV
            echo 'export CLOUDFLARE_API_TOKEN=$CF_WORKERS_API_TOKEN' >> $BASH_ENV
      - run:
          name: Publish the worker code
          command: npm run publish
workflows:
  publish:
    jobs:
      - test:
          context: org-global
      - publish:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - master
